

spring:
  application:
    name: user-management
  banner:
    location: classpath:/banners/banner.txt
    server:
      port: 9095

##########################sspring database

datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      databaseUrl:	jdbc:sqlserver://localhost;DatabaseName=friend_finder;characterEncoding=UTF-8;encrypt=false
      databaseUser:   sasa
      databasePassword:  sasasasa
      hibernateDDLAuto:  create
      hibernateDialect:  org.hibernate.dialect.SQLServer2012Dialect


##########################   JPA

jpa:
  show-sql:  true
  hibernate:
    generate-ddl: true
  hibernateDDLauto: create
  hibernateDialect: org.hibernate.dialect.SQLServer2012Dialect


