spring:
  application:
   name: ${SPRING.APPLICATION.NAME:user-management}
  banner:
    location: ${SPRING.BANNER:classpath:/banners/banner.txt}
  security:
   user:
     name: gado
     password: gado
  messages:
   basename: i18n/messages
   local-default:
server:
   port: ${SERVER.PORT:9095}

##########################sspring database

datasource:
   driverClassName: ${DATASOURCE.DRIVER.NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
   databaseUrl: ${DATASOURCE.DATABASE.URL:jdbc:sqlserver://localhost;ff_user_management=management;characterEncoding=UTF-8;encrypt=false}
   databaseUser: ${DATASOURCE.USER.NAME:root}
   databasePassword: ${DATASOURCE.USER.PASSWORD:gado}
   platform: ${DATASOURCE.PLATFORM:org.hibernate.dialect.SQLServer2012Dialect}

##########################   JPA

jpa:
  showSql: ${JPA.SHOW_SQL:true}
  hibernate:
   hibernateDDLAuto: ${JPA.HIBERNATE.DDL.AUTO:none}
   hibernateDialect: ${JPA.HIBERNATE.DIALECT:org.hibernate.dialect.SQLServer2012Dialect}
   create_empty_composites:
     enabled: ${JPA.HIBERNATE.EMPTY.COMPOSITES:true}


user-management:
    token:
      secret: dshfksdjhk#$^sfddsmnmcfdmn_++#@$fsdfmns,fs@$RGDSF$@%<<<.hfh
      access-token-time: 5h
      refresh-token-time: 2h


  # hibernateDDLAuto: create
#org.hibernate.dialect.MySQLDialect
