

spring:
  application:
    name: ${SPRING.APPLICATION.NAME:user-management}
  banner:
    location: ${SPRING.BANNER:classpath:/banners/banner.txt}
    server:
      port: 9095

##########################sspring database

datasource:
   driverClassName: ${DATASOURCE.DRIVE.NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
   databaseUrl: ${DATASOURCE.DATABASE.URL:jdbc:sqlserver://localhost;DatabaseName=user_management;characterEncoding=UTF-8;encrypt=false}
   databaseUser: ${DATASOURCE.USER.NAME:root}
   databasePassword: ${DATASOURCE.USER.PASSWORD:gado}
   platform: ${DATASOURCE.PLATFORM:org.hibernate.dialect.SQLServer2012Dialect}

##########################   JPA

jpa:
  showSql: ${JPA.SHOW_SQL:true}
  hibernate:
   hibernateDDLAuto: ${JPA.HIBERNATE.DDL.AUTO:none}
   hibernateDialect: ${JPA.HIBERNATE.DIALECT:org.hibernate.dialect.SQLServer2012Dialect}
   create_empty_composites:
     enable: ${JPA.HIBERNATE.EMPTY.COMPOSITES:true}



  # hibernateDDLAuto: create
#org.hibernate.dialect.MySQLDialect
