

spring:
  application:
    name: user-management
  banner:
    location: classpath:/banners/banner.txt
    server:
      port: 9095

##########################sspring database

datasource:
   driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
   databaseUrl: jdbc:sqlserver://localhost;DatabaseName=friend_finder;characterEncoding=UTF-8;encrypt=false
   databaseUser: root
   databasePassword: gado
   platform: org.hibernate.dialect.SQLServer2012Dialect

##########################   JPA

jpa:
  showSql: true
  hibernate:
   hibernateDDLAuto: none
   hibernateDialect: org.hibernate.dialect.SQLServer2012Dialect
   create_empty_composites:
     enable: true



  # hibernateDDLAuto: create
#org.hibernate.dialect.MySQLDialect
